AWSTemplateFormatVersion: '2010-09-09'
Description: Creates AWS Glue resources.  **WARNING**  You will be billed for the
  AWS resources used if you create a stack from this template.
Parameters:
  KinesisStreamBucketName:
    Description: Kinesis stream bucket name
    Type: String
  KinesisStreamKeyPrefix:
    Type: String
  GlueJobRole:
    Description: glue job role ARN
    Type: String
  CuratedBucketName:
    Description: s3 location for CuratedDatasetsDatabase
    Type: String
Resources:
  DatalakeSubmissionsDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Name: datalake_submissions
        Description: Data Lake Quick Start Submissions
  CuratedDatasetsDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Name: datalake_curated_datasets
        Description: Data Lake Quick Start Curated Datasets
  CMAPSSClassifier:
    Type: AWS::Glue::Classifier
    Properties:
      CsvClassifier:
        AllowSingleColumn: false
        ContainsHeader: ABSENT
        Delimiter: ' '
        Name: cmapss_classify
        QuoteSymbol: '"'
  CMAPSSSubmissions:
    Type: AWS::Glue::Crawler
    Properties:
      Name: "cmapss_submissions"
      Role: !Ref GlueJobRole
      DatabaseName: !Ref DatalakeSubmissionsDatabase
      Classifiers:
        - !Ref CMAPSSClassifier
      Targets:
        S3Targets:
          - Path: !Join
            - "/"
            - - !Ref "KinesisStreamBucketName"
              - !Ref "KinesisStreamKeyPrefix"
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
  CMAPSSCuratedRUL:
    Type: AWS::Glue::Crawler
    Properties:
      Name: "cmapss_curated_rul"
      Role: !Ref GlueJobRole
      DatabaseName: !Ref CuratedDatasetsDatabase
      Targets:
        S3Targets:
          - Path: !Ref "CuratedBucketName"
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
  CMAPSSJob:
    Type: AWS::Glue::Job
    Properties:
      GlueVersion: 2.0
      Command:
        Name: glueetl
        ScriptLocation: "../src/glue_job.py"
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 0
      Name: calc_rul
      Role: !Ref GlueJobRole
  Workflow:
    Type: AWS::Glue::Workflow
    Properties: 
      Description: Workflow for orchestrating jobs
      Name: CMapssWorkflow
  WorkflowStartTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: StartTrigger
      Type: ON_DEMAND
      Description: Trigger for starting the workflow
      Actions:
        - CrawlerName: !Ref CMAPSSSubmissions 
      WorkflowName: !Ref Workflow
  WorkflowJobTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: CrawlerSuccessfulTrigger
      Type: CONDITIONAL
      StartOnCreation: True
      Description: Trigger to start the glue job
      Actions:
        - JobName: !Ref CMAPSSJob
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            CrawlerName: !Ref CMAPSSSubmissions
            CrawlState: SUCCEEDED
      WorkflowName: !Ref Workflow
  WorkflowCrawlerTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: JobSuccessfulTrigger
      Type: CONDITIONAL
      StartOnCreation: True
      Description: Trigger to start the glue job
      Actions:
        - CrawlerName: !Ref CMAPSSCuratedRUL
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            JobName: !Ref CMAPSSJob
            State: SUCCEEDED
      WorkflowName: !Ref Workflow
Outputs:
  CuratedDatasetsDatabaseName:
    Value: !Ref 'CuratedDatasetsDatabase'
  DatalakeSubmissionsDatabaseName:
    Value: !Ref 'DatalakeSubmissionsDatabase'
