AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create IAM roles. (qs-1nlkhq1oj)
Resources:
  GlueJobRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - 'arn:aws:s3:::aws-bb-darren*/*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Join
                    - ''
                    - - !Ref 'SubmissionsBucketARN'
                      - /*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Join
                    - ''
                    - - !Ref 'PublishedDataARN'
                      - /*
                  - !Join
                    - ''
                    - - !Ref 'CuratedDatasetsARN'
                      - /*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Path: "/"
  KinesisStreamBucketRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref 'AWS::AccountId'
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Effect: Allow
                Resource: !Join
                  - ''
                  - - !Ref 'SubmissionsBucketARN'
                    - '*'
            Version: '2012-10-17'
          PolicyName: KinesisBucketAccess
    Type: AWS::IAM::Role
  LambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: arn:aws:logs:*:*:*
            Version: '2012-10-17'
          PolicyName: LambdaLogging
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject
                Effect: Allow
                Resource:
                  - !Join
                    - ''
                    - - !Ref 'SubmissionsBucketARN'
                      - /*
                  - !Join
                    - ''
                    - - !Ref 'CuratedDatasetsARN'
                      - /*
                  - !Join
                    - ''
                    - - !Ref 'PublishedDataARN'
                      - /*
            Version: '2012-10-17'
          PolicyName: GetObjectsDatalake
    Type: AWS::IAM::Role
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Path: /service-role/
      Policies:
        - PolicyName: CuratedBucketS3BucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub '${CuratedDatasetsARN}*'
        - PolicyName: SageMakerS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: 'VisualEditor0'
                Effect: Allow
                Action: s3:ListBucket
                Resource: arn:aws:s3:::SageMaker
              - Sid: 'VisualEditor1'
                Effect: Allow
                Action:
                  - s3:GetLifecycleConfiguration
                  - s3:ListBucketByTags
                  - s3:GetBucketTagging
                  - s3:GetInventoryConfiguration
                  - s3:GetObjectVersionTagging
                  - s3:GetBucketLogging
                  - s3:ListBucketVersions
                  - s3:GetAccelerateConfiguration
                  - s3:ListBucket
                  - s3:GetBucketPolicy
                  - s3:GetEncryptionConfiguration
                  - s3:GetObjectAcl
                  - s3:GetObjectVersionTorrent
                  - s3:GetBucketRequestPayment
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectTagging
                  - s3:GetMetricsConfiguration
                  - s3:GetIpConfiguration
                  - s3:ListBucketMultipartUploads
                  - s3:GetBucketWebsite
                  - s3:GetBucketVersioning
                  - s3:GetBucketAcl
                  - s3:GetBucketNotification
                  - s3:GetReplicationConfiguration
                  - s3:ListMultipartUploadParts
                  - s3:GetObject
                  - s3:GetObjectTorrent
                  - s3:GetBucketCORS
                  - s3:GetAnalyticsConfiguration
                  - s3:GetObjectVersionForReplication
                  - s3:GetBucketLocation
                  - s3:GetObjectVersio
                Resource: arn:aws:s3:::SageMaker/*
              - Sid: 'VisualEditor2'
                Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:HeadBucket
                Resource: '*'
Parameters:
  CuratedDatasetsARN:
    Description: CuratedDatasets bucket ARN
    Type: String
  PublishedDataARN:
    Description: PublishedData bucket ARN
    Type: String
  SubmissionsBucketARN:
    Description: SubmissionsBucket bucket ARN
    Type: String
Outputs:
  GlueJobRole:
    Description: ARN of GlueRole
    Value: !GetAtt 'GlueJobRole.Arn'
  LambdaRoleARN:
    Description: ARN of LambdaRole
    Value: !GetAtt 'LambdaRole.Arn'
  KinesisStreamBucketRoleARN:
    Description: ARN of KinesisStreamBucketRole
    Value: !GetAtt 'KinesisStreamBucketRole.Arn'
  SageMakerExecutionRoleARN:
    Description: Sage Maker Execution Role ARN
    Value: !GetAtt 'SageMakerExecutionRole.Arn'
